import { useState, useEffect, useRef } from "react";
import { motion } from "motion/react";
import {
  FileText,
  Calendar,
  Clock,
  DollarSign,
  FileDown,
  Loader2,
  FileBarChart,
  Sparkles,
  Eye,
  CheckCircle2,
  RefreshCw,
} from "lucide-react";
import useUserStore from "../../store/userStore";
import api from "../../api/axiosInstance";
import { useTranslation } from "react-i18next";

const authHeaders = () => {
  const token = useUserStore.getState().token;
  return token
    ? { headers: { Authorization: `Bearer ${token}` } }
    : {};
};

const INVOICE_TYPES = [
  { value: "", label: "All Invoices", icon: FileText },
  { value: "daily", label: "Daily", icon: Calendar },
  { value: "weekly", label: "Weekly", icon: Calendar },
  { value: "monthly", label: "Monthly", icon: Calendar },
  { value: "deposit", label: "Deposit", icon: DollarSign },
  { value: "withdrawal", label: "Withdrawal", icon: DollarSign },
  { value: "statement", label: "Statement", icon: FileBarChart },
];

export default function InvoicePage() {
  const { t } = useTranslation();
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterType, setFilterType] = useState("");
  const [generating, setGenerating] = useState(null);
  const [downloading, setDownloading] = useState(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const initialLoadDone = useRef(false);

  useEffect(() => {
    fetchInvoices();
  }, [filterType]);

  // Auto-generate on first load if no invoices exist
  useEffect(() => {
    if (!loading && invoices.length === 0 && !initialLoadDone.current) {
      initialLoadDone.current = true;
      autoGenerateFirstInvoice();
    }
  }, [loading, invoices]);

  const fetchInvoices = async () => {
    setLoading(true);
    try {
      const params = filterType ? `?invoice_type=${filterType}` : "";
      const res = await api.get(`v1/invoice/my${params}`, authHeaders());
      setInvoices(res?.data?.invoices || []);
    } catch (err) {
      console.error("Failed to fetch invoices:", err);
    } finally {
      setLoading(false);
    }
  };

  const autoGenerateFirstInvoice = async () => {
    setAutoGenerated(true);
    for (const type of ["statement", "daily"]) {
      try {
        const res = await api.get(`v1/invoice/${type}`, authHeaders());
        if (res?.data?.invoice) {
          setAutoGenerated(false);
          setInvoices((prev) => [res.data.invoice, ...prev]);
          return;
        }
      } catch {
        // Silently try next type
      }
    }
    setAutoGenerated(false);
  };

  const generateInvoice = async (type) => {
    setGenerating(type);
    try {
      const res = await api.get(`v1/invoice/${type}`, authHeaders());
      if (res?.data?.invoice) {
        setInvoices((prev) => [res.data.invoice, ...prev]);
      }
    } catch (err) {
      console.error(`Failed to generate ${type} invoice:`, err);
    } finally {
      setGenerating(null);
    }
  };

  const downloadInvoice = async (invoice) => {
    if (!invoice.id || !invoice.pdf_url) return;

    setDownloading(invoice.id);
    try {
      const token = useUserStore.getState().token;
      const baseUrl = api.defaults.baseURL || "";
      const apiBase = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;

      const downloadUrl = `${apiBase}/v1/invoice/download/${invoice.id}`;

      const response = await fetch(downloadUrl, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) throw new Error(`HTTP ${response.status}`);

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${invoice.invoice_number || "invoice"}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to download invoice:", err);
      try {
        const baseUrl = api.defaults.baseURL || "";
        const pdfUrl = `${baseUrl.replace("/api", "")}${invoice.pdf_url}`;
        window.open(pdfUrl, "_blank");
      } catch (fallbackErr) {
        console.error("Fallback download also failed:", fallbackErr);
      }
    } finally {
      setDownloading(null);
    }
  };

  const viewInvoice = async (invoice) => {
    if (!invoice.id || !invoice.pdf_url) return;

    setDownloading(invoice.id);
    try {
      const token = useUserStore.getState().token;
      const baseUrl = api.defaults.baseURL || "";
      const apiBase = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;

      const downloadUrl = `${apiBase}/v1/invoice/download/${invoice.id}`;

      const response = await fetch(downloadUrl, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) throw new Error(`HTTP ${response.status}`);

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank");
    } catch (err) {
      console.error("Failed to view invoice:", err);
      const baseUrl = api.defaults.baseURL || "";
      const pdfUrl = `${baseUrl.replace("/api", "")}${invoice.pdf_url}`;
      window.open(pdfUrl, "_blank");
    } finally {
      setDownloading(null);
    }
  };

  const formatDate = (iso) => {
    if (!iso) return "-";
    return new Date(iso).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const getTypeIcon = (type) => {
    const found = INVOICE_TYPES.find((t) => t.value === type);
    return found?.icon || FileText;
  };

  const getTypeColor = (type) => {
    switch (type) {
      case "daily": return "text-blue-400 bg-blue-500/10";
      case "weekly": return "text-cyan-400 bg-cyan-500/10";
      case "monthly": return "text-purple-400 bg-purple-500/10";
      case "deposit": return "text-green-400 bg-green-500/10";
      case "withdrawal": return "text-red-400 bg-red-500/10";
      case "statement": return "text-amber-400 bg-amber-500/10";
      default: return "text-gray-400 bg-gray-500/10";
    }
  };

  return (
    <div className="p-4 md:p-6 space-y-5">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold mb-1">
            <span className="bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
              {t("invoice.title")}
            </span>
          </h1>
          <p className="text-gray-400 text-sm">{t("invoice.subtitle")}</p>
        </div>
        <button
          onClick={fetchInvoices}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-white/5 border border-white/10 text-gray-400 hover:text-white hover:bg-white/10 transition-all"
        >
          <RefreshCw className="w-3 h-3" />
          {t("invoice.refresh")}
        </button>
      </div>

      {/* Auto-generating indicator */}
      {autoGenerated && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-2 px-4 py-3 rounded-xl bg-gradient-to-r from-blue-600/20 to-cyan-600/10 border border-blue-500/30 text-blue-300 text-sm"
        >
          <Sparkles className="w-4 h-4 animate-pulse" />
          {t("invoice.generatingFirst")}
        </motion.div>
      )}

      {/* Quick Generate Buttons */}
      <div>
        <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3 flex items-center gap-2">
          <Sparkles className="w-3 h-3" />
          {t("invoice.quickGenerate")}
        </h3>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
          {[
            { type: "daily", labelKey: "dailySummary", icon: Calendar, color: "from-blue-600/20 to-cyan-600/10 border-blue-500/30" },
            { type: "weekly", labelKey: "weeklySummary", icon: Calendar, color: "from-cyan-600/20 to-teal-600/10 border-cyan-500/30" },
            { type: "monthly", labelKey: "monthlySummary", icon: Calendar, color: "from-purple-600/20 to-violet-600/10 border-purple-500/30" },
            { type: "statement", labelKey: "fullStatement", icon: FileBarChart, color: "from-amber-600/20 to-orange-600/10 border-amber-500/30" },
          ].map((btn) => (
            <motion.button
              key={btn.type}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={() => generateInvoice(btn.type)}
              disabled={generating === btn.type}
              className={`p-4 rounded-xl bg-gradient-to-br ${btn.color} backdrop-blur-xl border hover:shadow-lg transition-all duration-300 flex flex-col items-center gap-2 ${generating === btn.type ? "opacity-60" : "hover:border-white/30"}`}
            >
              {generating === btn.type ? (
                <Loader2 className="w-5 h-5 text-white animate-spin" />
              ) : (
                <btn.icon className="w-5 h-5 text-white" />
              )}
              <span className="text-xs font-semibold text-white/80">
                {generating === btn.type ? t("invoice.generating") : t("invoice." + btn.labelKey)}
              </span>
            </motion.button>
          ))}
        </div>
      </div>

      {/* Filter */}
      <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
        <div className="flex gap-2 overflow-x-auto pb-1">
          {INVOICE_TYPES.map((type) => (
            <button
              key={type.value}
              onClick={() => setFilterType(type.value)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all whitespace-nowrap ${
                filterType === type.value
                  ? "bg-gradient-to-r from-blue-600 to-cyan-500 text-white"
                  : "bg-white/5 border border-white/10 text-gray-400 hover:text-white"
              }`}
            >
              <type.icon className="w-3 h-3" />
              {type.value ? t("invoice." + type.value) : t("invoice.allInvoices")}
            </button>
          ))}
        </div>
      </div>

      {/* Invoices List */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-xl bg-gradient-to-br from-white/[0.08] to-white/[0.02] backdrop-blur-xl border border-white/10 overflow-hidden"
      >
        <div className="p-4 md:p-5 border-b border-white/10">
          <h2 className="font-bold text-white flex items-center gap-2">
            <FileText className="w-4 h-4 text-cyan-400" />
            {t("invoice.yourInvoices")}
            <span className="text-xs text-gray-500 font-normal ml-2">
              ({invoices.length})
            </span>
          </h2>
        </div>

        {loading ? (
          <div className="p-8 text-center">
            <Loader2 className="w-6 h-6 animate-spin mx-auto mb-2 text-cyan-400" />
            <p className="text-gray-400 text-sm">{t("invoice.loadingInvoices")}</p>
          </div>
        ) : invoices.length === 0 && !autoGenerated ? (
          <div className="p-8 text-center">
            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500/20 to-cyan-500/10 flex items-center justify-center mx-auto mb-4">
              <FileText className="w-8 h-8 text-cyan-400" />
            </div>
            <p className="text-gray-300 font-semibold">{t("invoice.noInvoices")}</p>
            <p className="text-gray-500 text-xs mt-1 max-w-xs mx-auto">
              {t("invoice.noInvoicesDesc")}
            </p>
            <div className="flex flex-wrap gap-2 justify-center mt-4">
              <button
                onClick={() => generateInvoice("daily")}
                disabled={generating === "daily"}
                className="px-4 py-2 rounded-lg bg-gradient-to-r from-blue-600 to-cyan-500 text-white text-xs font-semibold hover:shadow-lg transition-all flex items-center gap-1.5"
              >
                {generating === "daily" ? (
                  <Loader2 className="w-3 h-3 animate-spin" />
                ) : (
                  <Sparkles className="w-3 h-3" />
                )}
                {t("invoice.generateDaily")}
              </button>
              <button
                onClick={() => generateInvoice("statement")}
                disabled={generating === "statement"}
                className="px-4 py-2 rounded-lg bg-white/10 border border-white/20 text-white text-xs font-semibold hover:bg-white/20 transition-all flex items-center gap-1.5"
              >
                {generating === "statement" ? (
                  <Loader2 className="w-3 h-3 animate-spin" />
                ) : (
                  <FileBarChart className="w-3 h-3" />
                )}
                {t("invoice.generateStatement")}
              </button>
            </div>
          </div>
        ) : (
          <div className="divide-y divide-white/5">
            {invoices.map((inv, idx) => {
              const Icon = getTypeIcon(inv.invoice_type);
              const colorClass = getTypeColor(inv.invoice_type);
              const isDownloading = downloading === inv.id;
              return (
                <motion.div
                  key={inv.id || idx}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: idx * 0.03 }}
                  className="p-4 md:p-5 flex items-center gap-4 hover:bg-white/[0.02] transition-colors"
                >
                  <div className={`w-10 h-10 rounded-xl ${colorClass} flex items-center justify-center flex-shrink-0`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold text-white text-sm truncate">
                      {inv.invoice_number}
                    </div>
                    <div className="flex items-center gap-3 text-xs text-gray-400 mt-0.5">
                      <span className="flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {formatDate(inv.created_at)}
                      </span>
                      {inv.amount !== null && inv.amount !== undefined && (
                        <span className="flex items-center gap-1">
                          <DollarSign className="w-3 h-3" />
                          ${Number(inv.amount).toFixed(2)}
                        </span>
                      )}
                    </div>
                  </div>
                  <span className={`hidden sm:inline px-2.5 py-1 rounded-full text-[10px] font-semibold ${colorClass}`}>
                    {inv.invoice_type?.charAt(0).toUpperCase() + inv.invoice_type?.slice(1)}
                  </span>
                  <span className={`px-2 py-0.5 rounded text-[10px] font-semibold ${
                    inv.status === "generated" ? "bg-green-500/10 text-green-400" :
                    inv.status === "failed" ? "bg-red-500/10 text-red-400" :
                    "bg-yellow-500/10 text-yellow-400"
                  }`}>
                    {inv.status === "generated" ? t("invoice.ready") : inv.status}
                  </span>

                  <button
                    onClick={() => viewInvoice(inv)}
                    disabled={!inv.pdf_url || isDownloading}
                    className={`p-2 rounded-lg transition-all ${
                      inv.pdf_url
                        ? "bg-white/5 hover:bg-blue-500/20 text-gray-400 hover:text-blue-400 border border-white/10 hover:border-blue-500/30"
                        : "bg-white/[0.02] text-gray-600 cursor-not-allowed"
                    }`}
                    title={t("invoice.viewPdf")}
                  >
                    {isDownloading ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <Eye className="w-4 h-4" />
                    )}
                  </button>

                  <button
                    onClick={() => downloadInvoice(inv)}
                    disabled={!inv.pdf_url || isDownloading}
                    className={`p-2 rounded-lg transition-all ${
                      inv.pdf_url
                        ? "bg-white/5 hover:bg-cyan-500/20 text-gray-400 hover:text-cyan-400 border border-white/10 hover:border-cyan-500/30"
                        : "bg-white/[0.02] text-gray-600 cursor-not-allowed"
                    }`}
                    title={t("invoice.downloadPdf")}
                  >
                    {isDownloading ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <FileDown className="w-4 h-4" />
                    )}
                  </button>
                </motion.div>
              );
            })}
          </div>
        )}
      </motion.div>

      {invoices.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-xl bg-gradient-to-br from-white/[0.08] to-white/[0.02] backdrop-blur-xl border border-white/10 p-4 md:p-5"
        >
          <h3 className="font-bold text-white text-sm flex items-center gap-2 mb-3">
            <CheckCircle2 className="w-4 h-4 text-green-400" />
            {t("invoice.needHelp")}
          </h3>
          <p className="text-gray-400 text-xs">
            {t("invoice.helpDesc")}
          </p>
        </motion.div>
      )}
    </div>
  );
}
