<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->call(RolesAndPermissionsSeeder::class);
        $this->call(DemoGamesSeeder::class);

        // Sample player account for local development / manual testing.
        // Password is generated by the factory (never hardcoded).
        $player = User::factory()->create([
            'name' => 'Sample Player',
            'email' => 'player@example.com',
        ]);
        $player->assignRole('player');
    }
}
