<?php

namespace Database\Seeders;

use App\Models\Game;
use App\Models\GameCategory;
use Illuminate\Database\Seeder;

class DemoGamesSeeder extends Seeder
{
    public function run(): void
    {
        $categories = $this->createCategories();
        $this->createGames($categories);
    }

    private function createCategories(): array
    {
        $categoryData = [
            ['name' => 'Arcade', 'slug' => 'arcade', 'icon' => 'gamepad-2', 'sort_order' => 1],
            ['name' => 'Cards', 'slug' => 'cards', 'icon' => 'layers', 'sort_order' => 2],
            ['name' => 'Dice', 'slug' => 'dice', 'icon' => 'dice-5', 'sort_order' => 3],
            ['name' => 'Wheel', 'slug' => 'wheel', 'icon' => 'circle-dot', 'sort_order' => 4],
            ['name' => 'Puzzle', 'slug' => 'puzzle', 'icon' => 'puzzle', 'sort_order' => 5],
            ['name' => 'Reaction', 'slug' => 'reaction', 'icon' => 'zap', 'sort_order' => 6],
            ['name' => 'Strategy', 'slug' => 'strategy', 'icon' => 'brain', 'sort_order' => 7],
            ['name' => 'Memory', 'slug' => 'memory', 'icon' => 'brain-cog', 'sort_order' => 8],
            ['name' => 'Number', 'slug' => 'number', 'icon' => 'hash', 'sort_order' => 9],
            ['name' => 'Casual', 'slug' => 'casual', 'icon' => 'smile', 'sort_order' => 10],
        ];

        $categories = [];
        foreach ($categoryData as $data) {
            $categories[$data['slug']] = GameCategory::create($data);
        }

        return $categories;
    }

    private function createGames(array $categories): void
    {
        $games = [
            // ═══════════════════════════════════════════
            // ARCADE (15 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Space Invaders',
                'slug' => 'space-invaders',
                'game_slug' => 'space-invaders',
                'description' => 'Classic arcade shooter. Destroy alien waves before they reach you.',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'is_featured' => true,
                'rules' => 'Move left/right and shoot. Destroy all aliens in each wave. Score increases with each kill. Game ends when aliens reach the bottom.',
                'config' => ['lives' => 3, 'speed' => 1, 'alien_rows' => 3, 'alien_cols' => 5],
            ],
            [
                'name' => 'Breakout',
                'slug' => 'breakout',
                'game_slug' => 'breakout',
                'description' => 'Smash all the bricks with the ball. Classic brick-breaking action.',
                'category' => 'arcade',
                'difficulty' => 'easy',
                'rules' => 'Move paddle to bounce the ball. Break all bricks. Ball speed increases over time. Lose a life if ball falls below paddle.',
                'config' => ['lives' => 3, 'brick_rows' => 5, 'brick_cols' => 8],
            ],
            [
                'name' => 'Snake',
                'slug' => 'snake',
                'game_slug' => 'snake',
                'description' => 'Guide the snake to eat food and grow longer. Don\'t hit the walls or yourself!',
                'category' => 'arcade',
                'difficulty' => 'easy',
                'is_featured' => true,
                'rules' => 'Use arrow keys or swipe to move. Eat food to grow. Score increases with each food eaten. Game ends if you hit a wall or yourself.',
                'config' => ['grid_size' => 20, 'initial_length' => 3],
            ],
            [
                'name' => 'Pong',
                'slug' => 'pong',
                'game_slug' => 'pong',
                'description' => 'Classic table tennis simulation. First to 11 wins!',
                'category' => 'arcade',
                'difficulty' => 'easy',
                'rules' => 'Move paddle up/down. Ball bounces off paddles and walls. Score when opponent misses. First to 11 points wins.',
                'config' => ['win_score' => 11, 'ball_speed' => 5],
            ],
            [
                'name' => 'Flappy Bird',
                'slug' => 'flappy-bird',
                'game_slug' => 'flappy-bird',
                'description' => 'Tap to fly through pipes. How far can you go?',
                'category' => 'arcade',
                'difficulty' => 'hard',
                'rules' => 'Tap or press space to flap. Navigate through pipe gaps. Score increases with each pipe passed. Game ends on collision.',
                'config' => ['gravity' => 0.5, 'flap_strength' => -8, 'pipe_gap' => 150],
            ],
            [
                'name' => 'Tetris',
                'slug' => 'tetris',
                'game_slug' => 'tetris',
                'description' => 'Stack falling blocks to clear lines. Classic puzzle arcade.',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'is_featured' => true,
                'rules' => 'Move and rotate falling blocks. Complete horizontal lines to clear them. Score increases with multiple line clears. Game ends when blocks reach the top.',
                'config' => ['grid_width' => 10, 'grid_height' => 20],
            ],
            [
                'name' => 'Asteroids',
                'slug' => 'asteroids',
                'game_slug' => 'asteroids',
                'description' => 'Navigate through space and destroy asteroids. Don\'t get hit!',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'rules' => 'Rotate and thrust your ship. Shoot to destroy asteroids. Large asteroids split into smaller ones. Score based on asteroid size.',
                'config' => ['lives' => 3, 'initial_asteroids' => 5],
            ],
            [
                'name' => 'Pac-Man',
                'slug' => 'pacman',
                'game_slug' => 'pacman',
                'description' => 'Eat all dots while avoiding ghosts. Power pellets let you eat ghosts!',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'rules' => 'Use arrow keys to move. Eat all dots to clear the level. Power pellets let you eat ghosts for bonus points. Avoid ghosts when not powered up.',
                'config' => ['lives' => 3, 'ghost_count' => 4],
            ],
            [
                'name' => 'Donkey Kong',
                'slug' => 'donkey-kong',
                'game_slug' => 'donkey-kong',
                'description' => 'Climb platforms and avoid barrels to reach the top.',
                'category' => 'arcade',
                'difficulty' => 'hard',
                'rules' => 'Climb ladders and jump over barrels. Reach the top platform to advance. Avoid barrel collisions. Score for jumping over barrels.',
                'config' => ['lives' => 3, 'barrel_speed' => 3],
            ],
            [
                'name' => 'Frogger',
                'slug' => 'frogger',
                'game_slug' => 'frogger',
                'description' => 'Help the frog cross roads and rivers safely.',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'rules' => 'Cross the road avoiding cars. Jump on logs to cross the river. Reach the safe zone at the top. Timer adds pressure.',
                'config' => ['lives' => 3, 'time_limit' => 60],
            ],
            [
                'name' => 'Galaga',
                'slug' => 'galaga',
                'game_slug' => 'galaga',
                'description' => 'Shoot down formations of aliens in this classic shooter.',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'rules' => 'Move and shoot to destroy alien formations. Aliens dive-bomb your ship. Chain kills for bonus points. Boss aliens take multiple hits.',
                'config' => ['lives' => 3, 'wave_count' => 10],
            ],
            [
                'name' => 'Centipede',
                'slug' => 'centipede',
                'game_slug' => 'centipede',
                'description' => 'Shoot the centipede as it winds down the screen.',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'rules' => 'Move and shoot. Centipede segments split when hit. Mushrooms slow the centipede. Spider and flea add extra danger.',
                'config' => ['lives' => 3, 'centipede_length' => 10],
            ],
            [
                'name' => ' Missile Command',
                'slug' => 'missile-command',
                'game_slug' => 'missile-command',
                'description' => 'Defend your cities from incoming missiles.',
                'category' => 'arcade',
                'difficulty' => 'hard',
                'rules' => 'Click to launch counter-missiles. Destroy incoming missiles before they hit cities. Protect all 6 cities to advance. Limited ammo.',
                'config' => ['cities' => 6, 'ammo' => 10],
            ],
            [
                'name' => 'Defender',
                'slug' => 'defender',
                'game_slug' => 'defender',
                'description' => 'Protect humans from alien abductors in this side-scrolling shooter.',
                'category' => 'arcade',
                'difficulty' => 'hard',
                'rules' => 'Scroll left/right to find aliens. Shoot aliens before they abduct humans. Rescue falling humans. Hyperspace to escape danger.',
                'config' => ['lives' => 3, 'humans_to_save' => 10],
            ],
            [
                'name' => 'Joust',
                'slug' => 'joust',
                'game_slug' => 'joust',
                'description' => 'Knights on ostriches battle in the air. L platform to win!',
                'category' => 'arcade',
                'difficulty' => 'medium',
                'rules' => 'Flap to gain altitude. L platform your opponent from above. L platform enemies to score. Survive all waves.',
                'config' => ['lives' => 3, 'enemies_per_wave' => 3],
            ],

            // ═══════════════════════════════════════════
            // CARDS (12 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Card Flip',
                'slug' => 'card-flip',
                'game_slug' => 'card-flip',
                'description' => 'Flip cards and find matching pairs. Test your memory!',
                'category' => 'cards',
                'difficulty' => 'easy',
                'is_featured' => true,
                'rules' => 'Click cards to flip them. Find all matching pairs. Fewest moves wins. Track your best score.',
                'config' => ['pairs' => 8, 'grid_cols' => 4],
            ],
            [
                'name' => 'Solitaire',
                'slug' => 'solitaire',
                'game_slug' => 'solitaire',
                'description' => 'Classic card game. Arrange cards by suit in ascending order.',
                'category' => 'cards',
                'difficulty' => 'medium',
                'rules' => 'Move cards between columns. Build foundation piles by suit. King can start new columns. Clear all cards to win.',
                'config' => ['draw_count' => 1],
            ],
            [
                'name' => 'Blackjack Demo',
                'slug' => 'blackjack-demo',
                'game_slug' => 'blackjack-demo',
                'description' => 'Get as close to 21 as possible without going over. Score-based only!',
                'category' => 'cards',
                'difficulty' => 'medium',
                'rules' => 'Get cards closer to 21 than the dealer. Face cards are 10, Aces are 1 or 11. Hit to draw, stand to hold. Score based on wins.',
                'config' => ['decks' => 1, 'dealer_stands_at' => 17],
            ],
            [
                'name' => 'Poker Hand Trainer',
                'slug' => 'poker-hand-trainer',
                'game_slug' => 'poker-hand-trainer',
                'description' => 'Learn poker hands by ranking them correctly.',
                'category' => 'cards',
                'difficulty' => 'medium',
                'rules' => 'Rank poker hands from highest to lowest. Learn Royal Flush, Straight Flush, Four of a Kind, etc. Score for correct rankings.',
                'config' => ['hands_per_round' => 5],
            ],
            [
                'name' => 'War',
                'slug' => 'card-war',
                'game_slug' => 'card-war',
                'description' => 'Classic card war. Higher card wins the round!',
                'category' => 'cards',
                'difficulty' => 'easy',
                'rules' => 'Both players reveal top card. Higher card wins both. Aces are highest. Track wins across multiple rounds.',
                'config' => ['rounds' => 26],
            ],
            [
                'name' => 'Go Fish',
                'slug' => 'go-fish',
                'game_slug' => 'go-fish',
                'description' => 'Ask for cards to make matching sets. Collect the most books!',
                'category' => 'cards',
                'difficulty' => 'easy',
                'rules' => 'Ask opponent for specific cards. Collect sets of 4 (books). If opponent doesn\'t have it, "go fish". Most books wins.',
                'config' => ['hand_size' => 7],
            ],
            [
                'name' => 'Memory Cards',
                'slug' => 'memory-cards',
                'game_slug' => 'memory-cards',
                'description' => 'Find all matching card pairs in the fastest time.',
                'category' => 'cards',
                'difficulty' => 'easy',
                'rules' => 'Flip two cards per turn. Match pairs to remove them. Clear the board in fewest moves. Timer tracks your speed.',
                'config' => ['pairs' => 10, 'grid_cols' => 5],
            ],
            [
                'name' => 'Cribbage Score',
                'slug' => 'cribbage-score',
                'game_slug' => 'cribbage-score',
                'description' => 'Score cribbage hands as fast as you can.',
                'category' => 'cards',
                'difficulty' => 'hard',
                'rules' => 'Identify scoring combinations in cribbage hands. Points for pairs, runs, fifteens, and flushes. Speed and accuracy count.',
                'config' => ['hands_per_round' => 10],
            ],
            [
                'name' => 'Hearts',
                'slug' => 'hearts',
                'game_slug' => 'hearts',
                'description' => 'Avoid taking hearts and the Queen of Spades. Lowest score wins!',
                'category' => 'cards',
                'difficulty' => 'hard',
                'rules' => 'Avoid winning tricks with hearts. Queen of Spades is 13 points. Shoot the moon to reverse scores. Lowest score wins.',
                'config' => ['target_score' => 100],
            ],
            [
                'name' => 'Spades',
                'slug' => 'spades',
                'game_slug' => 'spades',
                'description' => 'Bid and take tricks with your partner. Spades are always trump!',
                'category' => 'cards',
                'difficulty' => 'hard',
                'rules' => 'Bid how many tricks you\'ll take. Spades are always trump. Make your bid to score. Overtricks add bonus points.',
                'config' => ['target_score' => 500],
            ],
            [
                'name' => 'Euchre',
                'slug' => 'euchre',
                'game_slug' => 'euchre',
                'description' => 'Team card game with trump. Bid, then take tricks!',
                'category' => 'cards',
                'difficulty' => 'hard',
                'rules' => 'Bid on trump suit. Jack of trump is highest card. Team tries to take 3+ tricks. euchred opponents score extra.',
                'config' => ['target_score' => 10],
            ],
            [
                'name' => 'Crazy Eights',
                'slug' => 'crazy-eights',
                'game_slug' => 'crazy-eights',
                'description' => 'Match cards by suit or rank. Eights are wild!',
                'category' => 'cards',
                'difficulty' => 'easy',
                'rules' => 'Play cards matching suit or rank. Eights are wild (play any suit). First to empty hand wins. Draw if you can\'t play.',
                'config' => ['hand_size' => 7],
            ],

            // ═══════════════════════════════════════════
            // DICE (8 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Dice Roller',
                'slug' => 'dice-roller',
                'game_slug' => 'dice-roller',
                'description' => 'Roll virtual dice and see your luck. Track statistics!',
                'category' => 'dice',
                'difficulty' => 'easy',
                'rules' => 'Click to roll. See results and statistics. Track frequency of each number over many rolls.',
                'config' => ['dice_count' => 2, 'sides' => 6],
            ],
            [
                'name' => 'Dice Duel',
                'slug' => 'dice-duel',
                'game_slug' => 'dice-duel',
                'description' => 'You vs computer. Higher total wins the round!',
                'category' => 'dice',
                'difficulty' => 'easy',
                'rules' => 'Both players roll dice. Higher total wins the round. Track wins across multiple rounds. Best of 10 wins the match.',
                'config' => ['dice_count' => 2, 'rounds' => 10],
            ],
            [
                'name' => 'Yahtzee',
                'slug' => 'yahtzee',
                'game_slug' => 'yahtzee',
                'description' => 'Roll dice to make the best poker-like combinations.',
                'category' => 'dice',
                'difficulty' => 'medium',
                'rules' => 'Roll up to 3 times per turn. Choose which dice to keep. Score in category rows. Highest total score wins.',
                'config' => ['dice_count' => 5, 'rolls_per_turn' => 3],
            ],
            [
                'name' => 'Liar\'s Dice',
                'slug' => 'liars-dice',
                'game_slug' => 'liars-dice',
                'description' => 'Bluff about your dice rolls. Call out lies to win!',
                'category' => 'dice',
                'difficulty' => 'medium',
                'rules' => 'Roll dice secretly. Bid on total dice face value. Opponent can call "liar" or raise bid. Bluffing is key!',
                'config' => ['dice_count' => 5, 'rounds' => 5],
            ],
            [
                'name' => 'Ship Captain Crew',
                'slug' => 'ship-captain-crew',
                'game_slug' => 'ship-captain-crew',
                'description' => 'Roll to find Ship(6), Captain(5), Crew(4) then score with remaining dice.',
                'category' => 'dice',
                'difficulty' => 'easy',
                'rules' => 'Roll 5 dice. Must find 6, 5, 4 in order. Remaining 2 dice are your score. 3 rolls per turn. Highest score wins.',
                'config' => ['dice_count' => 5, 'rolls_per_turn' => 3],
            ],
            [
                'name' => 'Farkle',
                'slug' => 'farkle',
                'game_slug' => 'farkle',
                'description' => 'Roll dice for scoring combinations. Push your luck or bank your points!',
                'category' => 'dice',
                'difficulty' => 'medium',
                'rules' => 'Roll 6 dice. Score with 1s, 5s, or combinations. Can roll remaining dice for more points. Farkle (no scoring) loses turn points.',
                'config' => ['dice_count' => 6, 'target_score' => 10000],
            ],
            [
                'name' => 'Pig',
                'slug' => 'pig-dice',
                'game_slug' => 'pig-dice',
                'description' => 'Roll and accumulate points. Roll a 1 and lose everything!',
                'category' => 'dice',
                'difficulty' => 'easy',
                'rules' => 'Roll dice. Add to turn total. Can "hold" to bank points. Roll a 1 and lose turn total. First to 100 wins.',
                'config' => ['target_score' => 100],
            ],
            [
                'name' => 'Sevens',
                'slug' => 'sevens',
                'game_slug' => 'sevens',
                'description' => 'Roll dice trying to avoid sevens. Who cracks first?',
                'category' => 'dice',
                'difficulty' => 'easy',
                'rules' => 'Roll two dice. If total is 7, you lose. Otherwise add to your score. Can keep rolling or pass. Highest score without busting wins.',
                'config' => ['dice_count' => 2],
            ],

            // ═══════════════════════════════════════════
            // WHEEL (5 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Lucky Wheel',
                'slug' => 'lucky-wheel',
                'game_slug' => 'lucky-wheel',
                'description' => 'Spin the wheel and win points! How lucky are you?',
                'category' => 'wheel',
                'difficulty' => 'easy',
                'is_featured' => true,
                'rules' => 'Click to spin. Wheel lands on random segment. Points awarded based on segment. Track your total score.',
                'config' => ['segments' => 12, 'max_points' => 1000],
            ],
            [
                'name' => 'Wheel of Words',
                'slug' => 'wheel-of-words',
                'game_slug' => 'wheel-of-words',
                'description' => 'Spin to get letter values. Guess the word for bonus points!',
                'category' => 'wheel',
                'difficulty' => 'medium',
                'rules' => 'Spin for letter value. Guess consonants or buy vowels. Solve the word puzzle. Bankrupt loses your turn score.',
                'config' => ['rounds' => 5, 'starting_credits' => 500],
            ],
            [
                'name' => 'Prize Wheel',
                'slug' => 'prize-wheel',
                'game_slug' => 'prize-wheel',
                'description' => 'Spin to win prizes! Each spin is a surprise.',
                'category' => 'wheel',
                'difficulty' => 'easy',
                'rules' => 'Click to spin. Collect prizes in your inventory. Complete sets for bonus points. Spin limit per session.',
                'config' => ['spin_limit' => 20, 'prize_count' => 15],
            ],
            [
                'name' => 'Number Wheel',
                'slug' => 'number-wheel',
                'game_slug' => 'number-wheel',
                'description' => 'Spin two wheels. Match numbers to score!',
                'category' => 'wheel',
                'difficulty' => 'easy',
                'rules' => 'Spin both wheels. If numbers match, score big! Close numbers score small. Track your luck over many spins.',
                'config' => ['wheel_size' => 10, 'match_multiplier' => 10],
            ],
            [
                'name' => 'Color Wheel',
                'slug' => 'color-wheel',
                'game_slug' => 'color-wheel',
                'description' => 'Spin and predict the color. Correct guesses earn points!',
                'category' => 'wheel',
                'difficulty' => 'easy',
                'rules' => 'Predict the color before spinning. Correct prediction = points. Streak bonuses for consecutive correct guesses.',
                'config' => ['colors' => 6, 'streak_bonus' => 50],
            ],

            // ═══════════════════════════════════════════
            // PUZZLE (15 games)
            // ═══════════════════════════════════════════
            [
                'name' => '2048',
                'slug' => '2048',
                'game_slug' => '2048',
                'description' => 'Slide tiles and merge numbers to reach 2048!',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'is_featured' => true,
                'rules' => 'Swipe to move tiles. Matching numbers merge. Create 2048 tile to win. Board fills up = game over.',
                'config' => ['grid_size' => 4],
            ],
            [
                'name' => 'Sudoku',
                'slug' => 'sudoku',
                'game_slug' => 'sudoku',
                'description' => 'Fill the 9x9 grid with numbers 1-9. No repeats in rows, columns, or boxes!',
                'category' => 'puzzle',
                'difficulty' => 'hard',
                'is_featured' => true,
                'rules' => 'Fill empty cells with 1-9. No repeats in any row, column, or 3x3 box. Hint system available. Timer tracks your speed.',
                'config' => ['grid_size' => 9, 'hints' => 3],
            ],
            [
                'name' => 'Crossword',
                'slug' => 'crossword',
                'game_slug' => 'crossword',
                'description' => 'Fill in the crossword puzzle with the right words.',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Read clues and fill in words. Words intersect at shared letters. Complete all words to finish. Timer tracks speed.',
                'config' => ['grid_size' => 13, 'word_count' => 15],
            ],
            [
                'name' => 'Word Search',
                'slug' => 'word-search',
                'game_slug' => 'word-search',
                'description' => 'Find hidden words in the letter grid. Race against time!',
                'category' => 'puzzle',
                'difficulty' => 'easy',
                'rules' => 'Find words hidden in the grid. Words can go horizontally, vertically, or diagonally. Click and drag to select. Timer tracks speed.',
                'config' => ['grid_size' => 12, 'word_count' => 10],
            ],
            [
                'name' => 'Jigsaw Puzzle',
                'slug' => 'jigsaw-puzzle',
                'game_slug' => 'jigsaw-puzzle',
                'description' => 'Assemble the pieces to complete the picture.',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Drag pieces to correct positions. Pieces snap when placed correctly. Complete the image to win. Timer tracks speed.',
                'config' => ['pieces' => 25, 'image' => 'landscape'],
            ],
            [
                'name' => 'Minesweeper',
                'slug' => 'minesweeper',
                'game_slug' => 'minesweeper',
                'description' => 'Reveal safe squares and mark mines. Don\'t explode!',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Click to reveal squares. Numbers show adjacent mines. Right-click to flag mines. Clear all safe squares to win.',
                'config' => ['grid_size' => 10, 'mine_count' => 15],
            ],
            [
                'name' => 'Nonogram',
                'slug' => 'nonogram',
                'game_slug' => 'nonogram',
                'description' => 'Use number clues to paint the correct pattern.',
                'category' => 'puzzle',
                'difficulty' => 'hard',
                'rules' => 'Row and column clues tell you which cells to fill. Use logic to determine filled cells. Complete the picture to win.',
                'config' => ['grid_size' => 10],
            ],
            [
                'name' => 'Sliding Puzzle',
                'slug' => 'sliding-puzzle',
                'game_slug' => 'sliding-puzzle',
                'description' => 'Slide tiles to arrange them in order. Classic 15-puzzle!',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Click a tile adjacent to the empty space to slide it. Arrange numbers 1-15 in order. Fewest moves wins.',
                'config' => ['grid_size' => 4],
            ],
            [
                'name' => 'Tower of Hanoi',
                'slug' => 'tower-of-hanoi',
                'game_slug' => 'tower-of-hanoi',
                'description' => 'Move all discs to the last peg. Bigger discs can\'t go on smaller ones!',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Move one disc at a time. Larger discs cannot be placed on smaller ones. Move all discs to the target peg. Minimum moves = 2^n - 1.',
                'config' => ['disc_count' => 5],
            ],
            [
                'name' => 'Logic Grid',
                'slug' => 'logic-grid',
                'game_slug' => 'logic-grid',
                'description' => 'Use logic clues to solve the puzzle. Who owns the fish?',
                'category' => 'puzzle',
                'difficulty' => 'hard',
                'rules' => 'Read clues and eliminate possibilities. Fill in the grid to find the solution. Each clue eliminates options.',
                'config' => ['clue_count' => 15],
            ],
            [
                'name' => 'Cryptogram',
                'slug' => 'cryptogram',
                'game_slug' => 'cryptogram',
                'description' => 'Decode the encrypted quote by finding the letter substitutions.',
                'category' => 'puzzle',
                'difficulty' => 'hard',
                'rules' => 'Each letter is replaced with another. Use word patterns and frequency to decode. Complete the quote to win.',
                'config' => ['quote_length' => 50],
            ],
            [
                'name' => 'Tetromino Stack',
                'slug' => 'tetromino-stack',
                'game_slug' => 'tetromino-stack',
                'description' => 'Stack falling shapes to fill complete rows.',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Rotate and place falling shapes. Complete rows to clear them. Score increases with multi-row clears.',
                'config' => ['grid_width' => 8, 'grid_height' => 16],
            ],
            [
                'name' => 'Sokoban',
                'slug' => 'sokoban',
                'game_slug' => 'sokoban',
                'description' => 'Push boxes onto targets. Think carefully - you can\'t pull!',
                'category' => 'puzzle',
                'difficulty' => 'hard',
                'rules' => 'Push one box at a time. Push all boxes onto targets. You cannot pull boxes. Fewest moves wins.',
                'config' => ['level' => 1],
            ],
            [
                'name' => 'Pipe Puzzle',
                'slug' => 'pipe-puzzle',
                'game_slug' => 'pipe-puzzle',
                'description' => 'Connect all the pipes to complete the pipeline.',
                'category' => 'puzzle',
                'difficulty' => 'medium',
                'rules' => 'Rotate pipe segments to connect them. All pipes must be connected. Water must flow from start to end.',
                'config' => ['grid_size' => 6],
            ],
            [
                'name' => 'Light Up',
                'slug' => 'light-up',
                'game_slug' => 'light-up',
                'description' => 'Place light bulbs to illuminate all white cells.',
                'category' => 'puzzle',
                'difficulty' => 'hard',
                'rules' => 'Place bulbs that light horizontally and vertically. Black cells with numbers indicate adjacent bulbs. Light all white cells.',
                'config' => ['grid_size' => 8],
            ],

            // ═══════════════════════════════════════════
            // REACTION (8 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Reaction Test',
                'slug' => 'reaction-test',
                'game_slug' => 'reaction-test',
                'description' => 'How fast can you react? Click as soon as the color changes!',
                'category' => 'reaction',
                'difficulty' => 'easy',
                'is_featured' => true,
                'rules' => 'Wait for the color change. Click as fast as possible. Your reaction time is measured in milliseconds. Try to beat your best time.',
                'config' => ['rounds' => 5],
            ],
            [
                'name' => 'Color Match',
                'slug' => 'color-match',
                'game_slug' => 'color-match',
                'description' => 'Click when the text color matches the word. Stroop effect challenge!',
                'category' => 'reaction',
                'difficulty' => 'medium',
                'rules' => 'Click when the text color matches the word meaning. Ignore the word, focus on the color. Speed and accuracy matter.',
                'config' => ['rounds' => 20, 'time_limit' => 30],
            ],
            [
                'name' => 'Speed Click',
                'slug' => 'speed-click',
                'game_slug' => 'speed-click',
                'description' => 'Click as many targets as you can in the time limit!',
                'category' => 'reaction',
                'difficulty' => 'easy',
                'rules' => 'Click targets as they appear. Each click scores points. Bonus for consecutive hits. Misses reduce your streak.',
                'config' => ['time_limit' => 30, 'target_size' => 50],
            ],
            [
                'name' => 'Target Practice',
                'slug' => 'target-practice',
                'game_slug' => 'target-practice',
                'description' => 'Click the targets before they disappear. Accuracy counts!',
                'category' => 'reaction',
                'difficulty' => 'medium',
                'rules' => 'Targets appear and shrink. Click them before they disappear. Smaller targets = more points. Miss three and game over.',
                'config' => ['lives' => 3, 'target_speed' => 3],
            ],
            [
                'name' => 'Sequence Memory',
                'slug' => 'sequence-memory',
                'game_slug' => 'sequence-memory',
                'description' => 'Watch the sequence, then repeat it. How long can you remember?',
                'category' => 'reaction',
                'difficulty' => 'medium',
                'rules' => 'Watch the light sequence. Repeat it by clicking the buttons. Sequence gets longer each round. One mistake ends the game.',
                'config' => ['start_length' => 3],
            ],
            [
                'name' => 'Typing Speed',
                'slug' => 'typing-speed',
                'game_slug' => 'typing-speed',
                'description' => 'Type the words as fast as you can. Measure your WPM!',
                'category' => 'reaction',
                'difficulty' => 'easy',
                'rules' => 'Type the displayed words. Accuracy and speed both matter. Your WPM (words per minute) is calculated. Try to beat your record.',
                'config' => ['word_count' => 30, 'time_limit' => 60],
            ],
            [
                'name' => 'Reflex Arrow',
                'slug' => 'reflex-arrow',
                'game_slug' => 'reflex-arrow',
                'description' => 'Follow the arrows with the correct key. How fast can you go?',
                'category' => 'reaction',
                'difficulty' => 'medium',
                'rules' => 'Arrows appear on screen. Press the matching arrow key. Speed increases over time. Miss three and game over.',
                'config' => ['lives' => 3, 'start_speed' => 2],
            ],
            [
                'name' => 'Avoid the Wall',
                'slug' => 'avoid-the-wall',
                'game_slug' => 'avoid-the-wall',
                'description' => 'Dodge the incoming walls. How long can you survive?',
                'category' => 'reaction',
                'difficulty' => 'hard',
                'rules' => 'Walls approach from the right. Click to jump over gaps. Speed increases over time. Survive as long as possible.',
                'config' => ['speed' => 3, 'gap_size' => 100],
            ],

            // ═══════════════════════════════════════════
            // STRATEGY (10 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Tic Tac Toe',
                'slug' => 'tic-tac-toe',
                'game_slug' => 'tic-tac-toe',
                'description' => 'Classic Xs and Os. Get three in a row to win!',
                'category' => 'strategy',
                'difficulty' => 'easy',
                'is_featured' => true,
                'rules' => 'Take turns placing X or O. Get three in a row (horizontal, vertical, or diagonal) to win. Draw if board fills up.',
                'config' => ['grid_size' => 3],
            ],
            [
                'name' => 'Connect Four',
                'slug' => 'connect-four',
                'game_slug' => 'connect-four',
                'description' => 'Drop discs to get four in a row. Classic strategy game!',
                'category' => 'strategy',
                'difficulty' => 'medium',
                'rules' => 'Drop discs into columns. First to get four in a row (horizontal, vertical, diagonal) wins. Block your opponent!',
                'config' => ['cols' => 7, 'rows' => 6],
            ],
            [
                'name' => 'Othello',
                'slug' => 'othello',
                'game_slug' => 'othello',
                'description' => 'Flip your opponent\'s pieces. Most pieces on the board wins!',
                'category' => 'strategy',
                'difficulty' => 'medium',
                'rules' => 'Place pieces to flip opponent\'s pieces. All pieces between your new piece and existing piece flip. Most pieces at end wins.',
                'config' => ['grid_size' => 8],
            ],
            [
                'name' => 'Checkers',
                'slug' => 'checkers',
                'game_slug' => 'checkers',
                'description' => 'Classic board game. Jump and capture your opponent\'s pieces!',
                'category' => 'strategy',
                'difficulty' => 'medium',
                'rules' => 'Move diagonally. Jump over opponent pieces to capture. Reach the back row to become a King. Capture all opponent pieces to win.',
                'config' => ['grid_size' => 8],
            ],
            [
                'name' => 'Chess Puzzle',
                'slug' => 'chess-puzzle',
                'game_slug' => 'chess-puzzle',
                'description' => 'Solve chess puzzles. Checkmate in the fewest moves!',
                'category' => 'strategy',
                'difficulty' => 'hard',
                'rules' => 'Find the best move. Checkmate the king in the given number of moves. Hints available. Score for solving quickly.',
                'config' => ['puzzles_per_round' => 5],
            ],
            [
                'name' => 'Battleship',
                'slug' => 'battleship',
                'game_slug' => 'battleship',
                'description' => 'Find and sink your opponent\'s ships. Strategic guessing!',
                'category' => 'strategy',
                'difficulty' => 'medium',
                'rules' => 'Place your ships. Take turns guessing coordinates. Hit or miss. Sink all opponent ships to win. Track hits and misses.',
                'config' => ['grid_size' => 10, 'ships' => 5],
            ],
            [
                'name' => 'Nim',
                'slug' => 'nim',
                'game_slug' => 'nim',
                'description' => 'Take turns removing objects. Take the last one loses!',
                'category' => 'strategy',
                'difficulty' => 'medium',
                'rules' => 'Remove 1-3 objects from the pile. The player who takes the last object loses. Strategic play can guarantee a win.',
                'config' => ['initial_objects' => 15, 'max_remove' => 3],
            ],
            [
                'name' => 'Mastermind',
                'slug' => 'mastermind',
                'game_slug' => 'mastermind',
                'description' => 'Break the code! Guess the color sequence in 10 tries.',
                'category' => 'strategy',
                'difficulty' => 'hard',
                'rules' => 'Guess the 4-color code. Feedback: correct color & position (black), correct color wrong position (white). 10 attempts to crack the code.',
                'config' => ['code_length' => 4, 'colors' => 6, 'attempts' => 10],
            ],
            [
                'name' => 'Gomoku',
                'slug' => 'gomoku',
                'game_slug' => 'gomoku',
                'description' => 'Five in a row wins! Strategic stone placement.',
                'category' => 'strategy',
                'difficulty' => 'medium',
                'rules' => 'Place stones on the board. First to get 5 in a row (horizontal, vertical, diagonal) wins. Block your opponent!',
                'config' => ['grid_size' => 15],
            ],
            [
                'name' => 'Dots and Boxes',
                'slug' => 'dots-and-boxes',
                'game_slug' => 'dots-and-boxes',
                'description' => 'Draw lines to complete boxes. Most boxes wins!',
                'category' => 'strategy',
                'difficulty' => 'easy',
                'rules' => 'Draw lines between dots. Complete a box to score a point and go again. Most boxes at end wins.',
                'config' => ['grid_size' => 5],
            ],

            // ═══════════════════════════════════════════
            // MEMORY (8 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Simon Says',
                'slug' => 'simon-says',
                'game_slug' => 'simon-says',
                'description' => 'Repeat the color sequence. How long can you remember?',
                'category' => 'memory',
                'difficulty' => 'medium',
                'is_featured' => true,
                'rules' => 'Watch the sequence of colors. Repeat it by clicking the buttons. Sequence gets longer each round. One mistake ends the game.',
                'config' => ['colors' => 4, 'start_length' => 3],
            ],
            [
                'name' => 'Memory Tiles',
                'slug' => 'memory-tiles',
                'game_slug' => 'memory-tiles',
                'description' => 'Find all matching pairs of tiles. Train your memory!',
                'category' => 'memory',
                'difficulty' => 'easy',
                'rules' => 'Click tiles to flip them. Find all matching pairs. Fewest moves wins. Track your best score.',
                'config' => ['pairs' => 8, 'grid_cols' => 4],
            ],
            [
                'name' => 'Number Memory',
                'slug' => 'number-memory',
                'game_slug' => 'number-memory',
                'description' => 'Memorize the number sequence. Then type it back!',
                'category' => 'memory',
                'difficulty' => 'medium',
                'rules' => 'A number sequence appears briefly. Memorize it. Type it back correctly. Sequence gets longer each round.',
                'config' => ['start_length' => 3, 'display_time' => 2],
            ],
            [
                'name' => 'Color Memory',
                'slug' => 'color-memory',
                'game_slug' => 'color-memory',
                'description' => 'Remember which colors appeared and in what order.',
                'category' => 'memory',
                'difficulty' => 'medium',
                'rules' => 'Colors flash on screen. Remember the sequence. Click colors in the correct order. Speed and accuracy matter.',
                'config' => ['colors' => 6, 'start_length' => 3],
            ],
            [
                'name' => 'Card Memory',
                'slug' => 'card-memory',
                'game_slug' => 'card-memory',
                'description' => 'Flip cards and remember where each one is.',
                'category' => 'memory',
                'difficulty' => 'easy',
                'rules' => 'Click two cards to flip them. Remember their positions. Find all matching pairs. Fewest flips wins.',
                'config' => ['pairs' => 10, 'grid_cols' => 5],
            ],
            [
                'name' => 'Pattern Memory',
                'slug' => 'pattern-memory',
                'game_slug' => 'pattern-memory',
                'description' => 'Watch the pattern, then recreate it from memory.',
                'category' => 'memory',
                'difficulty' => 'medium',
                'rules' => 'A grid pattern lights up. Memorize it. Click the same cells to recreate. Pattern gets more complex each round.',
                'config' => ['grid_size' => 5, 'start_cells' => 3],
            ],
            [
                'name' => 'Word Memory',
                'slug' => 'word-memory',
                'game_slug' => 'word-memory',
                'description' => 'Remember the words that appeared. Test your verbal memory!',
                'category' => 'memory',
                'difficulty' => 'hard',
                'rules' => 'Words appear one at a time. Remember all of them. Type the words back. One wrong word ends the game.',
                'config' => ['display_time' => 2],
            ],
            [
                'name' => 'Visual Memory',
                'slug' => 'visual-memory',
                'game_slug' => 'visual-memory',
                'description' => 'Remember the positions of objects on the grid.',
                'category' => 'memory',
                'difficulty' => 'hard',
                'rules' => 'Objects appear on a grid briefly. Remember their positions. Click the correct cells. Grid gets larger each round.',
                'config' => ['grid_size' => 4, 'start_objects' => 3],
            ],

            // ═══════════════════════════════════════════
            // NUMBER (10 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Number Guess',
                'slug' => 'number-guess',
                'game_slug' => 'number-guess',
                'description' => 'Guess the secret number. Get hints after each guess!',
                'category' => 'number',
                'difficulty' => 'easy',
                'rules' => 'Guess a number between 1 and 100. Get "higher" or "lower" hints. Try to guess in fewest attempts. Track your average.',
                'config' => ['min' => 1, 'max' => 100, 'max_guesses' => 10],
            ],
            [
                'name' => 'Higher or Lower',
                'slug' => 'higher-or-lower',
                'game_slug' => 'higher-or-lower',
                'description' => 'Will the next number be higher or lower? Test your intuition!',
                'category' => 'number',
                'difficulty' => 'easy',
                'rules' => 'See a number. Guess if the next number is higher or lower. Streak bonuses for correct guesses. How long can you go?',
                'config' => ['number_range' => 100],
            ],
            [
                'name' => 'Math Challenge',
                'slug' => 'math-challenge',
                'game_slug' => 'math-challenge',
                'description' => 'Solve math problems as fast as you can!',
                'category' => 'number',
                'difficulty' => 'medium',
                'is_featured' => true,
                'rules' => 'Solve addition, subtraction, multiplication, or division problems. Speed and accuracy both count. Difficulty increases over time.',
                'config' => ['operations' => ['+', '-', '*', '/'], 'time_limit' => 60],
            ],
            [
                'name' => 'Fast Calculation',
                'slug' => 'fast-calculation',
                'game_slug' => 'fast-calculation',
                'description' => 'Race against time to solve math problems!',
                'category' => 'number',
                'difficulty' => 'hard',
                'rules' => 'Solve problems before time runs out. Each correct answer adds time. Wrong answers reduce time. How long can you survive?',
                'config' => ['start_time' => 30, 'time_per_correct' => 5],
            ],
            [
                'name' => 'Number Sequence',
                'slug' => 'number-sequence',
                'game_slug' => 'number-sequence',
                'description' => 'Find the pattern and predict the next number.',
                'category' => 'number',
                'difficulty' => 'medium',
                'rules' => 'See a sequence of numbers. Find the pattern. Enter the next number. Difficulty increases with each correct answer.',
                'config' => ['sequence_length' => 5],
            ],
            [
                'name' => 'Prime Finder',
                'slug' => 'prime-finder',
                'game_slug' => 'prime-finder',
                'description' => 'Identify prime numbers as fast as you can!',
                'category' => 'number',
                'difficulty' => 'medium',
                'rules' => 'Numbers appear one at a time. Click "Prime" or "Not Prime" quickly. Speed bonus for fast answers. Track accuracy.',
                'config' => ['time_limit' => 30, 'max_number' => 100],
            ],
            [
                'name' => 'Fibonacci',
                'slug' => 'fibonacci',
                'game_slug' => 'fibonacci',
                'description' => 'Complete the Fibonacci sequence. How far can you go?',
                'category' => 'number',
                'difficulty' => 'medium',
                'rules' => 'See the beginning of a Fibonacci sequence. Enter the next numbers. Difficulty increases as numbers get larger.',
                'config' => ['start_length' => 5],
            ],
            [
                'name' => 'Factor Battle',
                'slug' => 'factor-battle',
                'game_slug' => 'factor-battle',
                'description' => 'Find all factors of a number before time runs out!',
                'category' => 'number',
                'difficulty' => 'medium',
                'rules' => 'A number appears. Find all its factors. Type them correctly. Time limit decreases each round. Speed matters!',
                'config' => ['time_limit' => 30],
            ],
            [
                'name' => 'Digit Sum',
                'slug' => 'digit-sum',
                'game_slug' => 'digit-sum',
                'description' => 'Calculate the sum of digits as fast as possible!',
                'category' => 'number',
                'difficulty' => 'easy',
                'rules' => 'A number appears. Calculate the sum of its digits. Enter the answer quickly. Track your average time.',
                'config' => ['rounds' => 20, 'number_length' => 6],
            ],
            [
                'name' => 'Power of Two',
                'slug' => 'power-of-two',
                'game_slug' => 'power-of-two',
                'description' => 'Identify powers of two. Test your number sense!',
                'category' => 'number',
                'difficulty' => 'easy',
                'rules' => 'Numbers appear. Identify which are powers of two. Click Yes or No. Speed and accuracy both matter.',
                'config' => ['rounds' => 20, 'max_number' => 1000],
            ],

            // ═══════════════════════════════════════════
            // CASUAL (9 games)
            // ═══════════════════════════════════════════
            [
                'name' => 'Rock Paper Scissors',
                'slug' => 'rock-paper-scissors',
                'game_slug' => 'rock-paper-scissors',
                'description' => 'Classic hand game. Can you beat the computer?',
                'category' => 'casual',
                'difficulty' => 'easy',
                'is_featured' => true,
                'rules' => 'Choose rock, paper, or scissors. Rock beats scissors, scissors beats paper, paper beats rock. Track wins.',
                'config' => ['rounds' => 10],
            ],
            [
                'name' => 'Coin Flip',
                'slug' => 'coin-flip',
                'game_slug' => 'coin-flip',
                'description' => 'Flip a virtual coin. Track heads vs tails statistics!',
                'category' => 'casual',
                'difficulty' => 'easy',
                'rules' => 'Click to flip. See if it\'s heads or tails. Track your statistics over many flips. Is it really 50/50?',
                'config' => [],
            ],
            [
                'name' => 'Hangman',
                'slug' => 'hangman',
                'game_slug' => 'hangman',
                'description' => 'Guess the word before the hangman is complete!',
                'category' => 'casual',
                'difficulty' => 'medium',
                'rules' => 'Guess one letter at a time. Wrong guesses add to the hangman. Guess the word before 6 wrong guesses. Multiple categories.',
                'config' => ['max_wrong' => 6],
            ],
            [
                'name' => 'Typing Tutor',
                'slug' => 'typing-tutor',
                'game_slug' => 'typing-tutor',
                'description' => 'Practice typing and improve your speed. Fun and educational!',
                'category' => 'casual',
                'difficulty' => 'easy',
                'rules' => 'Type the displayed text. Accuracy and speed are measured. Track your WPM over time. Practice makes perfect.',
                'config' => ['text_length' => 50],
            ],
            [
                'name' => 'Trivia Quiz',
                'slug' => 'trivia-quiz',
                'game_slug' => 'trivia-quiz',
                'description' => 'Test your knowledge with trivia questions!',
                'category' => 'casual',
                'difficulty' => 'medium',
                'rules' => 'Answer trivia questions. Multiple choice format. Score for correct answers. Speed bonus for fast answers.',
                'config' => ['questions_per_round' => 10, 'time_per_question' => 15],
            ],
            [
                'name' => 'Word Scramble',
                'slug' => 'word-scramble',
                'game_slug' => 'word-scramble',
                'description' => 'Unscramble the letters to find the word!',
                'category' => 'casual',
                'difficulty' => 'medium',
                'rules' => 'See scrambled letters. Unscramble them to form a word. Track your score and time. Hint available.',
                'config' => ['words_per_round' => 10],
            ],
            [
                'name' => 'Anagram Solver',
                'slug' => 'anagram-solver',
                'game_slug' => 'anagram-solver',
                'description' => 'Find all the anagrams of the given word!',
                'category' => 'casual',
                'difficulty' => 'hard',
                'rules' => 'See a word. Find all words that can be made from its letters. Score based on word length and speed.',
                'config' => ['time_limit' => 60],
            ],
            [
                'name' => 'Story Builder',
                'slug' => 'story-builder',
                'game_slug' => 'story-builder',
                'description' => 'Build a story one word at a time. Creativity counts!',
                'category' => 'casual',
                'difficulty' => 'easy',
                'rules' => 'Start with a word. Add words to build a story. Creativity and coherence are judged. Share your story.',
                'config' => ['max_words' => 50],
            ],
            [
                'name' => 'Emoji Puzzle',
                'slug' => 'emoji-puzzle',
                'game_slug' => 'emoji-puzzle',
                'description' => 'Guess the phrase from the emoji clues!',
                'category' => 'casual',
                'difficulty' => 'medium',
                'rules' => 'See a sequence of emoji. Guess the phrase they represent. Multiple attempts allowed. Track your score.',
                'config' => ['puzzles_per_round' => 10],
            ],
        ];

        $sortOrder = 0;
        foreach ($games as $gameData) {
            $category = $categories[$gameData['category']] ?? null;

            Game::create([
                'provider_id' => null,
                'category_id' => $category?->id,
                'name' => $gameData['name'],
                'slug' => $gameData['slug'],
                'game_slug' => $gameData['game_slug'],
                'external_game_id' => 'builtin-' . $gameData['slug'],
                'game_type' => 'interactive',
                'difficulty' => $gameData['difficulty'] ?? 'medium',
                'thumbnail_url' => '/images/games/' . $gameData['slug'] . '.jpg',
                'banner_url' => '/images/games/' . $gameData['slug'] . '-banner.jpg',
                'description' => $gameData['description'],
                'rules' => $gameData['rules'] ?? null,
                'config' => $gameData['config'] ?? [],
                'is_active' => true,
                'is_featured' => $gameData['is_featured'] ?? false,
                'has_demo' => true,
                'sort_order' => $sortOrder++,
                'play_count' => 0,
                'max_score' => 0,
            ]);
        }
    }
}
